Repository Team9-RobotIX/AWS, pull requests merged in 2018-02, with the labels that each got.

#20 Improve configuration
  .gitignore
  .travis.yml
  README.md
  flaskapp/config.example.py
  flaskapp/flaskapp.py
Labels: bug, enhancement, ready for review

#22 Fix default values
  flaskapp/flaskapp.py
  flaskapp/tests.py
Labels: bug, ready for review

#29 Handle registration and login with hashed password
  flaskapp/flaskapp.py
  requirements.txt
Labels: Feature

#37 Refactor tests
  flaskapp/tests.py
Labels: ready for review

#36 Fix queue
  flaskapp/flaskapp.py
  flaskapp/tests.py
Labels: bug
